### ISSUE TITLE
进入回放界面  浏览器后退见面 出现如下界面

### ISSUE THREAD

**Issue by whitesweater** [yhf2000/SDUOJ-WEB-REACT#14]
![M1BI_GVS_X~)MD7JW51N`@D](https://user-images.githubusercontent.com/78199614/162581610-d5348288-9387-4de1-8ae0-c85126fb9ccb.png)

**Comment by yhf2000** [comment]
初步分析，原因为请求被 (disk cache)，导致在校验时间戳时出错。

解决方案：
1. 考虑进行特判，只在固定的区域进行时间校验
2. 判断请求是否为 cache
3. time error 页面增加特判，时间正常时跳转回之前的页面。

临时解决方案为，Disable Cache 或 直接重新访问主站链接。

**Comment by yhf2000** [comment]
fixed in [ba4dc72](https://github.com/yhf2000/SDUOJ-WEB-REACT/commit/ba4dc72f4079aded86e96bc7f1026e7df8181719)
