### ISSUE TITLE
界面缩放时需要优化

### ISSUE THREAD

**Issue by HYLazy** [yhf2000/SDUOJ-WEB-REACT#26]
很多人平时都是浏览器占半屏做题，但是半屏缩放时右上角用户信息会消失，没有显示关键信息，同时增加无用操作。
![图片](https://hyl-other-file.oss-cn-hangzhou.aliyuncs.com/Snipaste_2022-06-29_20-22-01.png)

**Comment by yhf2000** [comment]
在不缩减左边长度的基础上，只能用现在的方案或用老版的方案，如下图：
![QQ截图20221003005412](https://user-images.githubusercontent.com/25897885/193466283-887403bf-7b29-4fa8-9464-291446988656.png)

之后考虑缩减左边的长度
